### ISSUE TITLE
Gaussian Process Module

### ISSUE THREAD

**Issue by mjadiaz** [mjadiaz/toy-models#12]
Create a Gaussian Process Module to learn a surrogate model of the environment. In this way, our sampler, which can be the RL agent or an MCMC algorithm, uses the learned environment instead of the actual target function based on the uncertainty of the sample point.

The implementations that we can use are from:
- scikit-learn: https://scikit-learn.org/stable/modules/gaussian_process.html 
- GPytorch: https://docs.gpytorch.ai/en/stable/examples/01_Exact_GPs/Simple_GP_Regression.html
- GPJax: https://gpjax.readthedocs.io/en/latest/examples/regression.html

the latest one has nice documentation. The module should have a package structure with example Jupiter notebooks or scripts and the source code of the module in an src folder, to make it installable with pip.

**Comment by GiorgioCerro** [comment]
Comments for next time:

- try error in predicting if no fit has been done
- change how to initialise the model (both the model and the data)

**Comment by GiorgioCerro** [comment]
The basic gp model is working. We can pass external data and it learns updating an internal database. Then we can predict along with a std. 

Note: we can't get 0std on training data. Is this due to hyper parameters or what? Need to investigate.
